language: node_js
node_js:
  - '12'
addons:
  apt:
    update: true
    packages:
      - xvfb
before_install:
  - echo $MapboxAccessToken | cut -f 2 -d . | base64 -d
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - npm test
